
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
   
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    working_dir: /app/backend
      
    volumes:
      - ./backend:/app/backend
  
    depends_on:
      - redis
      - celery  
      - postgres
    command: uv run python manage.py runserver 0.0.0.0:8000


  celery:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    command: uv run celery -A backend worker --loglevel=info
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=backend.settings
    volumes:
      - ./backend:/app/backend
    
  
    depends_on:
      - redis


  
  redis:
    build:
      context: redis-dir
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    command: redis-server /app/redis.conf
    
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    working_dir: /app/backend
    command: uv run celery -A backend flower
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=backend.settings
    volumes:
      - ./backend:/app/backend

    depends_on: 
      - redis
      - celery
  

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/djsite.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/ssl.key:/etc/ssl/private/ssl.key
    depends_on:
      - web
    restart: always

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: Tharunkumar
      POSTGRES_PASSWORD: tharun123
      POSTGRES_DB: web_compilation_service_db
    ports:
      - "5432:5432"

    volumes:
      - datap:/var/lib/postgresql/data/
    restart: always
volumes:
  datap: