
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: tharunkumar453/web
   
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    working_dir: /app/backend
    
  
    depends_on:
      - redis
      - celery  
      - postgres
    command:
      - uv
      - run
      - gunicorn
      - backend.wsgi:application
      - --bind
      - 0.0.0.0:8000
      - --workers
      - "2"
      - --threads
      - "2"
      - --timeout
      - "100"
      - --keep-alive
      - "5"
      - --worker-tmp-dir
      - /dev/shm
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: tharunkumar453/celery
    working_dir: /app/backend
    command: uv run celery -A backend worker --loglevel=info
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      - redis
    restart: always


  
  redis:
    build:
      context: redis-dir
      dockerfile: Dockerfile
    image: tharunkumar453/redis
    ports:
      - "6379:6379"
    command: redis-server /app/redis.conf
    
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    image: tharunkumar453/flower
    ports:
      - "5555:5555"
    working_dir: /app/backend
    command: uv run celery -A backend flower
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on: 
      - redis
      - celery


  nginx:
    build: ./nginx
    image: tharunkumar453/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always

  postgres:
    image: postgres:16-alpine

    environment:
      POSTGRES_USER: Tharunkumar
      POSTGRES_PASSWORD: tharun123
      POSTGRES_DB: web_compilation_service_db
    ports:
      - "5432:5432"

    restart: always
    
volumes:
  my_dj_data: