upstream django{
server  web:8000; 
}
server{
listen 80;
listen 443 ssl;

ssl_certificate /etc/nginx/ssl-keys/server.crt;
ssl_certificate_key /etc/nginx/ssl-keys/server.key;

server_name 20.212.14.87;

location /{
proxy_pass http://django;


# optional for backends only for the servers which generate pages proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
}
}

