# Generated by Django 6.0.2 on 2026-02-20 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="problem_table",
            fields=[
                (
                    "problem_id",
                    models.SlugField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("Problem_discription", models.TextField(blank=True, null=True)),
                ("test_cases", models.FileField(upload_to="testcase/")),
            ],
        ),
        migrations.CreateModel(
            name="submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "submission_id",
                    models.SlugField(max_length=20, serialize=False, unique=True),
                ),
                ("language_used", models.CharField(max_length=20)),
                ("time_of_submission", models.TimeField(auto_now_add=True)),
                ("code_file", models.FileField(upload_to="submissions/")),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="compile.problem_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("has_done", models.BooleanField(default=False)),
                ("language_used", models.CharField(max_length=20)),
                ("time_of_submission", models.TimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userboards",
                        to="compile.problem_table",
                    ),
                ),
            ],
        ),
    ]
