# Generated by Django 6.0.2 on 2026-03-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.SlugField(max_length=37, serialize=False, unique=True),
        ),
    ]
