name: ci-cd workflows

on:
  push:
    branches: [main]
jobs:
  job-build:
    runs-on: ubuntu-latest
    steps:
      - name: dump code from github to temp os 
        uses: actions/checkout@v4
     
   
      - name : Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name : Build images onky not run containers 
        run: docker compose build

      - name : Push images to DockerHub
        run: docker compose push
        
  job-deploy:
    runs-on: ubuntu-latest
    needs: job-build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create SSH key file
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        
    - name: push yml file to server
      run: scp -o StrictHostKeyChecking=no -i ssh_key.pem ./docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/TharunKumar/
      
    - name: push djconf file to server
      run: scp -o StrictHostKeyChecking=no -i ssh_key.pem ./nginx/djsite.conf ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/TharunKumar/
      
    - name: Deploy to remote server
      run: |
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
        mkdir -p ~/TharunKumar
        cd ~/TharunKumar
        sudo docker compose pull
        sudo docker compose up -d 
        EOF